name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint:ci
        env:
          MARKPROMPT_PROJECT_KEY: ${{ secrets.MARKPROMPT_PROJECT_KEY }}
          NEXT_PUBLIC_MARKPROMPT_PROJECT_KEY:
            ${{ secrets.MARKPROMPT_PROJECT_KEY }}

  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm build:packages
      - run: pnpm turbo run test
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  bundle-size:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - uses: preactjs/compressed-size-action@v2
        with:
          install-script: 'pnpm install --no-frozen-lockfile'
          build-script: '"build:packages"'
          pattern: '{./packages/**/dist/**/*.{cjs,js},./packages/css/markprompt.css}'
          exclude: '{**/*.map,**/*.d.{ts,cts},**/node_modules/**,./packages/**/node_modules/**/dist/**/*,./packages/eslint-config/dist/**/*}'
